### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by AdamOnAir** [AdamOnAir/vdl#41]
- [ ]  Icons
- [ ] Images upside-down (win Bug)
- [ ] Text color and size
- [ ] Keyboard glX
- [ ] glX Frame Buffer
- [ ] glX
